name: Deploy Pelican site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican markdown ghp-import

      - name: Build Pelican site
        run: pelican content

      - name: Deploy to GitHub Pages
        run: |
          ghp-import output -b gh-pages
          git push origin gh-pages
