name: Deploy Pelican site to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice
    - name: Checkout code
      uses: actions/checkout@v2

    # Aggiungi il token GitHub come credenziale per il push
    - name: Set up GitHub Token
      run: git config --global user.name "github-actions[bot]" && git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Aggiungi un pull per integrare le modifiche remote nel ramo gh-pages
    - name: Pull latest changes from gh-pages branch
      run: |
        git fetch origin
        git checkout gh-pages
        git pull origin gh-pages

    # Esegui la generazione del sito Pelican
    - name: Build the site
      run: pelican content

    # Esegui il deploy con ghp-import e push delle modifiche nel ramo gh-pages
    - name: Deploy to GitHub Pages
      run: |
        ghp-import output -b gh-pages
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages --force
